apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: node-descheduler
spec:
  version: {{ .TagName }}
  platforms:
    - bin: kubectl-node_descheduler.exe
      {{addURIAndSha "https://github.com/hornwind/kubectl-node-descheduler/releases/download/{{ .TagName }}/kubectl-node-descheduler_Windows_x86_64.zip" .TagName | indent 6 }}
      selector:
        matchLabels:
          os: windows
          arch: amd64
    - bin: kubectl-node_descheduler.exe
      {{addURIAndSha "https://github.com/hornwind/kubectl-node-descheduler/releases/download/{{ .TagName }}/kubectl-node-descheduler_Windows_arm64.zip" .TagName | indent 6 }}
      selector:
        matchLabels:
          os: windows
          arch: arm64
    - bin: kubectl-node_descheduler
      {{addURIAndSha "https://github.com/hornwind/kubectl-node-descheduler/releases/download/{{ .TagName }}/kubectl-node-descheduler_Linux_x86_64.tar.gz" .TagName | indent 6 }}
      selector:
        matchLabels:
          os: linux
          arch: amd64
    - bin: kubectl-node_descheduler
      {{addURIAndSha "https://github.com/hornwind/kubectl-node-descheduler/releases/download/{{ .TagName }}/kubectl-node-descheduler_Linux_arm64.tar.gz" .TagName | indent 6 }}
      selector:
        matchLabels:
          os: linux
          arch: arm64
    - bin: kubectl-node_descheduler
      {{addURIAndSha "https://github.com/hornwind/kubectl-node-descheduler/releases/download/{{ .TagName }}/kubectl-node-descheduler_Darwin_x86_64.tar.gz" .TagName | indent 6 }}
      selector:
        matchLabels:
          os: darwin
          arch: amd64
    - bin: kubectl-node_descheduler
      {{addURIAndSha "https://github.com/hornwind/kubectl-node-descheduler/releases/download/{{ .TagName }}/kubectl-node-descheduler_Darwin_arm64.tar.gz" .TagName | indent 6 }}
      selector:
        matchLabels:
          os: darwin
          arch: arm64
  shortDescription: Node-descheduler allows you to gracefully deschedule pods from nodes.
  homepage: https://github.com/hornwind/kubectl-node-descheduler
  description: Node-descheduler allows you to gracefully deschedule pods from nodes.
