name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_AUTH_TOKEN: ${{ secrets.GORELEASER_AUTH_TOKEN}}
      - name: Upload conditioner.yaml artifact
        uses: actions/upload-artifact@v4
        with:
          name: conditioner-yaml
          path: dist/krew/conditioner.yaml
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.47
